services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  nginx:
    build: .
    ports:
      - "127.0.0.1:10080:80"
      - "127.0.0.1:10443:443"
    depends_on:
      - frontend
      - backend
