services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"

  nginx:
    build: .
    ports:
      - "192.168.0.10:80:80"
      - "192.168.0.10:443:443"
    depends_on:
      - frontend
      - backend
